# infra/local/docker-compose.yaml

version: "3.8"

services:
  local-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: score
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
  local-redis:
    image: redis:6
    ports:
      - 6379:6379
  local-aws:
    image: localstack/localstack:1.2
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=4567
      - AWS_DEFAULT_REGION=ap-northeast-2
      - USE_SSL=0
    ports:
      - 4566:4566